SYS_EXIT = 0 # G1=CODE
SYS_READ = 1 # G1=FD, G2=LEN, G3=BUF(PTR)   RETURNS: G0=BYTES_READ
SYS_WRITE = 2 # G1=FD, G2=LEN, G3=MSG(PTR)  RETURNS: G0=BYTES_WROTE
SYS_OPENF = 3 # G1=FILENAME, G2=MODE, G3=FLAGS  RETUNS: G0=FD
SYS_CLOSEF = 4 # G1=FD  RETUNS: G0=CLOSED? (BOOL 0=FALSE, 1=TRUE)